#spring.datasource.url: jdbc:h2:mem:camunda-h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

spring:
  jersey:
    application-path: engine-rest
  jpa:
    show-sql: true
  datasource:
    url: jdbc:h2:file:./h2-database;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    baseline-version: 0
    baseline-on-migrate: true
    table: SCHEMA_VERSION
    locations: 'classpath:db.migration'

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    job-execution:
      max-wait: 3000

springdoc:
  swagger-ui.path: swagger-ui.html

exporter:
  batchSize: 1000
  interval: 2
  type: h2